import {createSlice} from '@reduxjs/toolkit';

// basic example slice copied from the docs
const dataMealSlice = createSlice({
  name: 'counter',
  initialState: {
    value: {
      data: [
        {
          id: '1',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '3',
          month: '5',
          year: '2022',
          check: 1,
          date: '19',
          day: '5',
          price: '200000',
          status: '2',
        },
        {
          id: '2',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '3',
          month: '5',
          year: '2022',
          check: 21,
          date: '20',
          day: '5',
          price: '600000',
          status: '2',
        },
        {
          id: '3',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '7',
          month: '6',
          year: '2022',
          check: 1,
          date: '1',
          day: '4',
          price: '500000',
          status: '2',
        },
        {
          id: '4',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 1,
          date: '18',
          day: '4',
          price: '200000',
          status: '2',
        },
        {
          id: '5',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 32,
          date: '23',
          day: '2',
          price: '800000',
          status: '1',
        },
        {
          id: '6',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 1,
          date: '17',
          day: '3',
          price: '400000',
          status: '2',
        },
        {
          id: '7',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 1,
          date: '19',
          day: '5',
          price: '440000',
          status: '0',
        },
        {
          id: '8',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '5',
          month: '5',
          year: '2022',
          check: 1,
          date: '20',
          day: '5',
          price: '120000',
          status: '2',
        },
        {
          id: '9',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '2',
          month: '6',
          year: '2022',
          check: 1,
          date: '1',
          day: '4',
          price: '330000',
          status: '2',
        },
        {
          id: '10',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 32,
          date: '23',
          day: '2',
          price: '100000',
          status: '1',
        },
        {
          id: '11',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '2',
          month: '5',
          year: '2022',
          check: 1,
          date: '24',
          day: '4',
          price: '330000',
          status: '2',
        },
        {
          id: '12',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 32,
          date: '24',
          day: '2',
          price: '100000',
          status: '1',
        },
        {
          id: '13',
          name: 'bữa trưa',
          checkMeal: 1,
          quantity: '2',
          month: '5',
          year: '2022',
          check: 43,
          date: '25',
          day: '4',
          price: '330000',
          status: '2',
        },
        {
          id: '14',
          name: 'bữa tối',
          checkMeal: 2,
          quantity: '1',
          month: '5',
          year: '2022',
          check: 35,
          date: '25',
          day: '2',
          price: '100000',
          status: '1',
        },
      ],
    },
  },
  reducers: {
    uploadQuantity: (state: any, action: any) => {
      state.value.data = state.value.data.map((el: any) => {
        const found = action.payload.find((s: any) => s.id === el.id);
        if (found) {
          el = Object.assign({}, el, found);
        }
        return el;
      });
    },
  },
});

// destructure actions and reducer from the slice (or you can access as dataCheckSlice.actions)

// export individual action creator functions
export const {uploadQuantity} = dataMealSlice.actions;

// often the reducer is a default export, but that doesn't matter
export default dataMealSlice.reducer;
